package inventory

import (
	"fmt"
	"sort"
	"strings"

	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/util/sets"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	"k8s.io/kubernetes/pkg/controlplane"
)

var (
	// nonResourceKinds are Kubernetes types that exist in the client-go scheme but are not
	// top-level REST resources: subresource-only types, discovery meta types, and internal
	// streaming/status types. This list is small and stable across releases.
	nonResourceKinds = sets.New(
		// subresource-only types (accessible only under a parent resource path)
		"Eviction",
		"NodeProxyOptions",
		"PodAttachOptions",
		"PodExecOptions",
		"PodPortForwardOptions",
		"PodProxyOptions",
		"RangeAllocation",
		"Scale",
		"SerializedReference",
		"ServiceProxyOptions",
		"TokenRequest",
		// discovery meta types (served at /api and /apis, not as regular resources)
		"APIGroup",
		"APIVersions",
		// internal streaming type used for watch responses, not a REST resource
		"WatchEvent",
		// error/status envelope, not a REST resource
		"Status",
		// internal pod phase type, not served
		"PodStatusResult",
	)

	// extraKubernetesAPIs are Kubernetes resources from separate vendored packages
	// (apiextensions-apiserver, kube-aggregator) that are not discoverable via
	// DefaultAPIResourceConfigSource and the client-go scheme.
	extraKubernetesAPIs = []ServedAPIEntry{
		{Group: "apiextensions.k8s.io", Version: "v1", Resource: "customresourcedefinitions", Kind: "CustomResourceDefinition"},
		{Group: "apiregistration.k8s.io", Version: "v1", Resource: "apiservices", Kind: "APIService"},
	}
)

func shouldSkipKind(kind string) bool {
	if strings.HasSuffix(kind, "List") {
		return true
	}
	if strings.HasSuffix(kind, "Options") {
		return true
	}
	// Note: do NOT filter on "Review" suffix. TokenReview, SubjectAccessReview,
	// SelfSubjectAccessReview etc. are real top-level POST endpoints.
	return nonResourceKinds.Has(kind)
}

// GenerateKubernetesInventory derives the base set of Kubernetes API resources
// from the vendored scheme and DefaultAPIResourceConfigSource.
func GenerateKubernetesInventory() ([]ServedAPIEntry, error) {
	resourceConfig := controlplane.DefaultAPIResourceConfigSource()
	result := []ServedAPIEntry{}

	for gv, enabled := range resourceConfig.GroupVersionConfigs {
		if !enabled {
			continue
		}
		for kind := range clientgoscheme.Scheme.KnownTypes(gv) {
			if shouldSkipKind(kind) {
				continue
			}
			plural, _ := meta.UnsafeGuessKindToResource(gv.WithKind(kind))

			result = append(result, ServedAPIEntry{
				Group:    plural.Group,
				Version:  plural.Version,
				Resource: plural.Resource,
				Kind:     kind,
			})
		}
	}

	result = append(result, extraKubernetesAPIs...)

	// Sort by (Group, Version, Resource) for stable diffs
	sort.Slice(result, func(i, j int) bool {
		if result[i].Group != result[j].Group {
			return result[i].Group < result[j].Group
		}
		if result[i].Version != result[j].Version {
			return result[i].Version < result[j].Version
		}
		return result[i].Resource < result[j].Resource
	})

	return result, nil
}

// FormatGoCode formats the inventory as Go code for a version-specific generated file.
// The file registers itself via init() so no central switch statement needs updating.
func FormatGoCode(entries []ServedAPIEntry, kubeMinorVersion int) (string, error) {
	var b strings.Builder

	fmt.Fprintf(&b, "// Code generated by test/extended/apiserver/inventory/write-kube-api-inventory. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package inventory\n\n")

	// Generate init function that registers this version (at the top for visibility)
	fmt.Fprintf(&b, "func init() {\n")
	fmt.Fprintf(&b, "\tRegisterKubernetesAPIs(\"1.%d\", kubeAPIs1%d)\n", kubeMinorVersion, kubeMinorVersion)
	fmt.Fprintf(&b, "}\n\n")

	// Generate the variable for this Kubernetes version
	fmt.Fprintf(&b, "var kubeAPIs1%d = []ServedAPIEntry{\n", kubeMinorVersion)
	for _, e := range entries {
		fmt.Fprintf(&b, "\t{Group: %q, Version: %q, Resource: %q, Kind: %q},\n",
			e.Group, e.Version, e.Resource, e.Kind)
	}
	fmt.Fprintf(&b, "}\n")

	return b.String(), nil
}
